GET http://localhost:5000/notes

###

GET http://localhost:5000/notes/cyUh7er4C4vuCyXK

###

POST http://localhost:5000/notes
Content-Type: application/json

{
    "title": "Awikwok",
    "tags": "aa",
    "body": "Male"
}

###

PUT http://localhost:5000/notes/cyUh7er4C4vuCyXK
Content-Type: application/json

{
    "title": "Awikwok",
    "tags": "vvvaa",
    "body": "Male"
}

###

DELETE http://localhost:5000/notes/cyUh7er4C4vuCyXK
Content-Type: application/json
